# Descomposicion de matrices

**Descomponer una matriz**: Quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original y que tengan ciertas propiedades.
Una matriz $A$ la podemos escribir como: sus autovectores producto punto una matriz diagonal, donde la matriz diagonal tiene todos los autovalores encontrados, producto punto la matriz inversa de sus autovectores.

**A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))**

Descomposición 2: 
* Restricciones: Nuestra Matriz $A$ sea real y simétrica (A = A-transpuesta). Decimos que A = la matriz de autovectores producto punto la matriz diagonal con los autovalores, producto punto la transpuesta de la matriz de autovectores. NOTA: Calcular la transpuesta de una matriz es mucho más económico en cómputo que calcular la inversa de una matriz. Y hay que recordar que el cómputo cuesta dinero.
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)

In [ ]:
import numpy as np


In [ ]:
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [ ]:
autovalores,autovectores = np.linalg.eig(A) 

print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [ ]:
A_calc= autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
A_calc

array([[3., 2.],
       [4., 1.]])

In [ ]:
A = np.array([[3,2],[2,3]])
A

array([[3, 2],
       [2, 3]])

In [ ]:
print(A==A.T)

[[ True  True]
 [ True  True]]


In [ ]:
autovalores,autovectores= np.linalg.eig(A)
print(autovalores)
print(autovectores)


[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
A_calc

array([[3., 2.],
       [2., 3.]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e4a76e78-c18a-4fc7-af6b-dc86cc664138' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>