In [ ]:
%matplotlib inline

In [ ]:
import numpy as np

A = np.array([[1,2,3],[3,4,5]])

A


array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
U,D,V = np.linalg.svd(A)

In [ ]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [ ]:
print(D)

[7.97638869 0.61418515]


In [ ]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [ ]:
print(D)

[7.97638869 0.61418515]


In [ ]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [ ]:
A=print((U.dot(D)).dot(V))

ValueError: shapes (2,) and (3,3) not aligned: 2 (dim 0) != 3 (dim 0)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e4a76e78-c18a-4fc7-af6b-dc86cc664138' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>