In [ ]:
%matplotlib inline

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt

np.set_printoptions(suppress=True)

In [ ]:
A = np.array([[1,2],[3,4],[5,6]])

U,D,V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)

U
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
D
[9.52551809 0.51430058]
V
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
D_pse= np.zeros((A.shape[0],A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("Valores a reemplazar en D_pse")

print(D_pse[:D.shape[0],:D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [ ]:
print("Valores que pondremps en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondremps en D_pse
[[0.10498117 0.        ]
 [0.         1.94438824]]


In [ ]:
D_pse[:D.shape[0],:D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)


[[0.10498117 0.         0.        ]
 [0.         1.94438824 0.        ]]


In [ ]:
A_pse = V.T.dot(D_pse).dot(U.T)
A_pse

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

In [ ]:
A_pse_calc=np.linalg.pinv(A)
A_pse_calc

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [ ]:
A_pse_calc.dot(A)


array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:

np.set_printoptions(suppress=False)
A_pse_calc.dot(A)


array([[ 1.00000000e+00, -1.77635684e-15],
       [ 4.44089210e-16,  1.00000000e+00]])

Las pseudo Inversas no son Conmutativas


In [ ]:
A.dot(A_pse_calc)


array([[ 0.25773196,  0.43298969, -0.06185567],
       [ 0.43298969,  0.74742268,  0.03608247],
       [-0.06185567,  0.03608247,  0.99484536]])

In [ ]:
A = np.array([[1,2],[3,4],[5,6]])
A_pse=np.linalg.pinv(A)
A_pse

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e4a76e78-c18a-4fc7-af6b-dc86cc664138' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>